import React, { useState } from "react";
import { Sparkles, Calendar, Droplet, ArrowRightLeft, RefreshCw, Eye, ListOrdered, ClipboardList, Check } from "lucide-react";
import { motion } from "motion/react";
import { DietPlan, DayPlan, UserProfile } from "../types";
import { createCalendarEvent, CalendarEventPayload } from "../lib/workspace";
import { getAccessToken, auth } from "../lib/firebase";

interface MealPlanViewProps {
  dietPlan: DietPlan;
  userProfile: UserProfile;
  onReOnboard: () => void;
}

export default function MealPlanView({ dietPlan, userProfile, onReOnboard }: MealPlanViewProps) {
  const [activeDay, setActiveDay] = useState(1);
  const currentDayPlan = dietPlan?.days?.find(d => d.dayNumber === activeDay) || dietPlan?.days?.[0];
  
  const [syncing, setSyncing] = useState(false);
  const [syncSuccess, setSyncSuccess] = useState<string | null>(null);

  const handleSyncToCalendar = async () => {
    const token = await getAccessToken();
    if (!token || !auth.currentUser) {
      alert("Please sign in with Google first on the settings/auth screen to use Google Calendar.");
      return;
    }

    const confirmed = window.confirm(
      `Add Day ${currentDayPlan.dayNumber} (${currentDayPlan.dayName}) meal times to your Google Calendar?`
    );
    if (!confirmed) return;

    setSyncing(true);
    setSyncSuccess(null);

    try {
      const today = new Date();
      const getIsoString = (hour: number, minute: number) => {
        const d = new Date(today);
        d.setHours(hour, minute, 0, 0);
        return d.toISOString();
      };

      const mealTimes = [
        { name: "Breakfast ☀️", meal: currentDayPlan.breakfast, start: getIsoString(8, 30), end: getIsoString(9, 15) },
        { name: "Lunch 🍱", meal: currentDayPlan.lunch, start: getIsoString(13, 0), end: getIsoString(14, 0) },
        { name: "Evening Snack ☕", meal: currentDayPlan.snacks, start: getIsoString(17, 30), end: getIsoString(18, 0) },
        { name: "Dinner 🌙", meal: currentDayPlan.dinner, start: getIsoString(20, 30), end: getIsoString(21, 30) },
      ];

      for (const item of mealTimes) {
        const event: CalendarEventPayload = {
          summary: `Aahar AI: ${item.name} - ${item.meal.name}`,
          description: `Wellness Goal: ${userProfile.onboardingData?.healthGoal || "Indian Clinical Wellness"}\nPortion: ${item.meal.portionSize}\nCalories: ${item.meal.calories} kcal\nProtein: ${item.meal.protein}g | Carbs: ${item.meal.carbs}g | Fat: ${item.meal.fat}g\n\nGenerated by Aahar AI.`,
          start: {
            dateTime: item.start,
            timeZone: "Asia/Kolkata",
          },
          end: {
            dateTime: item.end,
            timeZone: "Asia/Kolkata",
          }
        };
        await createCalendarEvent(token, event);
      }

      setSyncSuccess(`Day ${currentDayPlan.dayNumber} meal slots synced to Google Calendar!`);
      setTimeout(() => setSyncSuccess(null), 5000);
    } catch (e: any) {
      console.error(e);
      alert("Failed to sync to Google Calendar. Please check connection and try again.");
    } finally {
      setSyncing(false);
    }
  };

  return (
    <div id="one-week-plan-page" className="space-y-6 pb-28">
      {/* Header and Controls */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-display font-extrabold text-white tracking-tight drop-shadow-[0_2px_4px_rgba(0,0,0,0.85)]">
            Your 7-Day Indian Diet Plan
          </h2>
          <p className="text-xs text-emerald-100 mt-1 font-mono uppercase tracking-wider drop-shadow-[0_1.5px_2px_rgba(0,0,0,0.95)]">
            Optimized for {userProfile.onboardingData?.healthGoal.replace("_", " ")} • {userProfile.onboardingData?.regionalPreference} Style
          </p>
        </div>

        <div className="flex flex-wrap gap-2">
          <button
            onClick={handleSyncToCalendar}
            disabled={syncing}
            className="px-4 py-2 rounded-xl bg-mecha-green/10 border border-mecha-neon/30 hover:border-mecha-neon/60 text-mecha-neon hover:text-white transition-all text-xs font-mono font-medium flex items-center gap-2 cursor-pointer shadow-lg disabled:opacity-50"
          >
            {syncing ? (
              <div className="w-3.5 h-3.5 border-2 border-mecha-neon border-t-transparent rounded-full animate-spin" />
            ) : (
              <Calendar className="w-3.5 h-3.5" />
            )}
            <span className="drop-shadow-[0_1px_1px_rgba(0,0,0,0.8)]">
              {syncing ? "Syncing..." : "Sync Day to Calendar"}
            </span>
          </button>

          <button
            onClick={onReOnboard}
            className="px-4 py-2 rounded-xl bg-black/50 border border-glass-border hover:border-mecha-neon/40 text-bamboo-beige hover:text-white transition-all text-xs font-mono font-medium flex items-center gap-2 cursor-pointer shadow-lg"
          >
            <RefreshCw className="w-3.5 h-3.5 text-mecha-neon" />
            <span className="drop-shadow-[0_1px_1px_rgba(0,0,0,0.8)]">Regenerate AI Plan</span>
          </button>
        </div>
      </div>

      {syncSuccess && (
        <div className="p-3 bg-mecha-green/15 border border-mecha-neon/30 text-mecha-neon text-xs font-mono rounded-xl flex items-center gap-2 animate-bounce">
          <Check className="w-4 h-4 shrink-0" />
          <span>{syncSuccess}</span>
        </div>
      )}

      {/* General Advice Banner */}
      <div className="glass-panel rounded-3xl p-5 border border-mecha-neon/15 bg-gradient-to-r from-forest-brew to-black/30 relative overflow-hidden">
        <div className="absolute right-3 top-3">
          <Sparkles className="w-5 h-5 text-mecha-neon opacity-35" />
        </div>
        <div className="flex gap-4">
          <div className="w-10 h-10 rounded-xl bg-mecha-neon/10 border border-mecha-neon/20 flex items-center justify-center shrink-0 text-mecha-neon">
            <ClipboardList className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-xs font-mono uppercase tracking-widest text-bamboo-beige font-bold">Nutritionist Advice</h4>
            <p className="text-xs text-tea-mist leading-relaxed mt-1">{dietPlan.generalAdvice || "Maintain standard water intake, focus on eating raw salads before main lunch, and enjoy organic unsweetened green tea."}</p>
          </div>
        </div>
      </div>

      {/* Days Tabs (Day 1 to 7) */}
      <div className="flex gap-1.5 overflow-x-auto pb-2 scrollbar-thin">
        {dietPlan.days.map((day) => (
          <button
            key={day.dayNumber}
            onClick={() => setActiveDay(day.dayNumber)}
            className={`px-4 py-3 rounded-2xl border text-xs font-semibold shrink-0 transition-all cursor-pointer flex flex-col items-center gap-1 min-w-[70px] ${
              activeDay === day.dayNumber
                ? 'bg-gradient-to-b from-mecha-green/20 to-mecha-green/5 border-mecha-neon text-mecha-neon shadow-lg shadow-mecha-neon/5'
                : 'bg-black/40 border-glass-border text-tea-mist/70 hover:text-white hover:border-glass-border-hover'
            }`}
          >
            <span className="text-[10px] uppercase font-mono tracking-wider opacity-60">Day {day.dayNumber}</span>
            <span className="text-sm">{day.dayName.substring(0, 3)}</span>
          </button>
        ))}
      </div>

      {/* Day summary stats */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        {[
          { label: "Target Calories", val: `${currentDayPlan.totalCalories} kcal` },
          { label: "Target Protein", val: `${currentDayPlan.totalProtein} g` },
          { label: "Target Carbs", val: `${currentDayPlan.totalCarbs} g` },
          { label: "Target Fat", val: `${currentDayPlan.totalFat} g` },
          { label: "Water Goal", val: `${currentDayPlan.waterTargetLiters} Liters` }
        ].map((stat, idx) => (
          <div key={idx} className="glass-panel rounded-2xl p-3 text-center border border-glass-border/30">
            <span className="text-[9px] font-mono uppercase tracking-widest text-tea-mist block mb-1">{stat.label}</span>
            <span className="text-sm font-bold text-white font-mono">{stat.val}</span>
          </div>
        ))}
      </div>

      {/* Interactive Meal Breakdowns (Detailed recipe cards) */}
      <div className="space-y-4">
        <h4 className="text-xs font-mono uppercase tracking-widest text-bamboo-beige font-bold flex items-center gap-2">
          <Calendar className="w-4 h-4 text-mecha-neon" /> Daily Routine Breakdown
        </h4>

        <div className="space-y-4">
          {[
            { tag: "Morning Fuel ☀️", meal: currentDayPlan.breakfast, type: "Breakfast" },
            { tag: "Nourishing Lunch 🍱", meal: currentDayPlan.lunch, type: "Lunch" },
            { tag: "Midday Spark ☕", meal: currentDayPlan.snacks, type: "Evening Snacks" },
            { tag: "Evening Repair 🌙", meal: currentDayPlan.dinner, type: "Dinner" }
          ].map((item, index) => {
            const m = item.meal || { name: "Indian Diet Dish", description: "Healthy traditional preparation", calories: 300, protein: 12, carbs: 40, fat: 8, portionSize: "1 bowl" };
            return (
              <motion.div 
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                key={index}
                className="glass-panel rounded-2xl p-5 border border-glass-border flex flex-col md:flex-row justify-between gap-4 md:items-center relative"
              >
                <div className="space-y-1.5 max-w-xl">
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-mono uppercase tracking-widest text-mecha-neon bg-mecha-green/10 border border-mecha-green/20 px-2 py-0.5 rounded">
                      {item.tag}
                    </span>
                    <span className="text-xs text-tea-mist font-mono">{item.type}</span>
                  </div>
                  
                  <h5 className="text-lg font-bold text-white leading-snug">{m.name}</h5>
                  <p className="text-xs text-tea-mist leading-relaxed font-sans">{m.description}</p>
                </div>

                <div className="flex flex-col md:items-end justify-between shrink-0 border-t md:border-t-0 md:border-l border-glass-border/30 pt-3 md:pt-0 md:pl-5 gap-2">
                  <div className="text-left md:text-right">
                    <span className="text-xs text-bamboo-beige font-mono block md:text-right text-left">Portion: {m.portionSize}</span>
                  </div>

                  <div className="flex flex-wrap gap-2 text-[10px] font-mono">
                    <span className="px-2 py-1 bg-black/40 rounded border border-glass-border/30 text-white font-bold">{m.calories} kcal</span>
                    <span className="px-2 py-1 bg-black/40 rounded border border-glass-border/30 text-emerald-300">P: {m.protein}g</span>
                    <span className="px-2 py-1 bg-black/40 rounded border border-glass-border/30 text-amber-300">C: {m.carbs}g</span>
                    <span className="px-2 py-1 bg-black/40 rounded border border-glass-border/30 text-rose-300">F: {m.fat}g</span>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
